CREATE DATABASE IF NOT EXISTS dropwin;
use dropwin;

-- 캘린더 DB
DROP TABLE IF EXISTS calendar;
CREATE TABLE IF NOT EXISTS calendar(
	CALENDAR_NO INT AUTO_INCREMENT PRIMARY KEY,  -- 자동 증가 키로 대체
    CALENDAR_TITLE VARCHAR(1000) NOT NULL,
    CALENDAR_START DATETIME NOT NULL,
    CALENDAR_END DATETIME NOT NULL,
    ALL_DAY BOOLEAN NOT NULL
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

ALTER TABLE calendar MODIFY COLUMN calendar_end DATETIME NULL;

ALTER TABLE calendar
ADD COLUMN MEMBERS_ID VARCHAR(100) NOT NULL;

ALTER TABLE calendar
ADD CONSTRAINT fk_calendar_members
FOREIGN KEY (MEMBERS_ID)
REFERENCES members(id)
ON DELETE CASCADE
ON UPDATE CASCADE;

-- 인덱스 추가 (성능 향상 목적)
CREATE INDEX idx_calendar_members_id ON calendar(MEMBERS_ID);


INSERT INTO calendar (CALENDAR_TITLE, CALENDAR_START, CALENDAR_END, ALL_DAY)
VALUES ('회의 일정', '2025-07-15 10:00:00', '2025-07-15 11:00:00', false);
commit;

select * from calendar;
