DROP TABLE IF EXISTS bids;
DROP TABLE IF EXISTS FAVORITES;
DROP TABLE ITEMS_DETAIL;
DROP TABLE items;

CREATE TABLE items (
    id INT AUTO_INCREMENT PRIMARY KEY,
    category VARCHAR(50) NOT NULL,
    name VARCHAR(255) NOT NULL,
    start_price INT NOT NULL,
    current_price INT NOT NULL DEFAULT 0, -- 현재가 (0으로 초기화)
    buy_now_price INT,
    end_time DATETIME NOT NULL,
    image_paths VARCHAR(1024),
    transaction_method VARCHAR(50),
    return_policy TEXT,
    status VARCHAR(20) NOT NULL DEFAULT 'pending',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    seller_id VARCHAR(100),
    bid_count INT DEFAULT 0,
    is_paid BOOLEAN DEFAULT FALSE -- ⭐⭐ 추가: 결제 완료 여부 ⭐⭐
);


CREATE TABLE ITEMS_DETAIL (
    ITEM_ID INT PRIMARY KEY,
    SIZE VARCHAR(255),
    RELEASE_YEAR INT,
    COUNTRY VARCHAR(255),
    MATERIAL VARCHAR(255),
    ITEM_CONDITION VARCHAR(255),
    COLOR VARCHAR(255),
    BRAND VARCHAR(255),
    FEATURES TEXT,
    FOREIGN KEY (ITEM_ID) REFERENCES ITEMS(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE FAVORITES (
    FAVORITE_ID INT AUTO_INCREMENT PRIMARY KEY,
    USER_ID VARCHAR(20) NOT NULL,
    ITEM_ID INT NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_FAVORITES_USER_ID FOREIGN KEY (USER_ID) REFERENCES MEMBERS(id) ON DELETE CASCADE,
    CONSTRAINT FK_FAVORITES_ITEM_ID FOREIGN KEY (ITEM_ID) REFERENCES ITEMS(id) ON DELETE CASCADE
);

CREATE TABLE bids (
    id INT AUTO_INCREMENT PRIMARY KEY,
    item_id INT NOT NULL,
    user_id VARCHAR(20) NOT NULL,
    bid_price INT NOT NULL,
    bid_time DATETIME DEFAULT CURRENT_TIMESTAMP,
    status VARCHAR(50) NOT NULL DEFAULT '입찰 중', -- ⭐⭐ 추가: 입찰 상태 ⭐⭐
    FOREIGN KEY (item_id) REFERENCES items(id),
    FOREIGN KEY (user_id) REFERENCES members(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

SELECT * FROM ITEMS;
SELECT * FROM ITEMS_DETAIL;
SELECT * FROM BIDS;
SELECT * FROM FAVORITES;

 TRUNCATE TABLE items_detail;
 TRUNCATE TABLE items;