CREATE TABLE FAVORITES (
    FAVORITE_ID NUMBER PRIMARY KEY,
    USER_ID VARCHAR2(20) NOT NULL,
    ITEM_ID NUMBER NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP,
    CONSTRAINT FK_FAVORITES_USER_ID FOREIGN KEY (USER_ID) REFERENCES MEMBERS(USER_ID) ON DELETE CASCADE,
    CONSTRAINT FK_FAVORITES_ITEM_ID FOREIGN KEY (ITEM_ID) REFERENCES ITEMS(ITEM_ID) ON DELETE CASCADE
);

CREATE SEQUENCE FAVORITES_SEQ
START WITH 1
INCREMENT BY 1
NOCACHE
NOCYCLE;
